export const messageConstants = {
    SEND_EMAIL_REQUEST: 'MESSAGES_SEND_EMAIL_REQUEST',
    SEND_EMAIL_SUCCESS: 'MESSAGES_SEND_EMAIL_SUCCESS',
    SEND_EMAIL_FAILURE: 'MESSAGES_SEND_EMAIL_FAILURE',

    GET_EMAILS_REQUEST: 'MESSAGES_GET_EMAILS_REQUEST',
    GET_EMAILS_SUCCESS: 'MESSAGES_GET_EMAILS_SUCCESS',
    GET_EMAILS_FAILURE: 'MESSAGES_GET_EMAILS_FAILURE',

    CLEAR_EMAILS_STATE: 'MESSAGES_CLEAR_EMAILS_STATE',

    DELETE_EMAIL_REQUEST: 'MESSAGES_DELETE_EMAIL_REQUEST',
    DELETE_EMAIL_SUCCESS: 'MESSAGES_DELETE_EMAIL_SUCCESS',
    DELETE_EMAIL_FAILURE: 'MESSAGES_DELETE_EMAIL_FAILURE',
};
